# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform SFTPGo installation tasks
  when: sftpgo_enabled | bool
  tags:
    - setup-all
    - setup-sftpgo
    - install-all
    - install-sftpgo
  block:
    - name: Validate SFTPGo configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install SFTPGo
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform SFTPGo uninstallation tasks
  when: not sftpgo_enabled | bool
  tags:
    - setup-all
    - setup-sftpgo
  block:
    - name: Uninstall SFTPGo
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
