# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
# See: https://github.com/sftpgo/sftpgo_search_server/blob/master/bin/passwd.sh and https://sftpgo.net/faq/#password-reset-while-sftpgo-is-running
- name: Ensure SFTPGo admin password is set
  ansible.builtin.command:
    cmd: |-
      {{ devture_systemd_docker_base_host_command_docker }} exec {{ sftpgo_identifier }}
      sftpgo_search_server/bin/passwd.sh {{ sftpgo_conf_password }}
  register: result
  changed_when: "'Password successfully changed' in result.stdout"
  no_log: true
