# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of SFTPGo systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ sftpgo_identifier }}.service"
  register: sftpgo_service_stat

- name: Uninstall SFTPGo systemd services and files
  when: sftpgo_service_stat.stat.exists | bool
  block:
    - name: Ensure SFTPGo systemd service is stopped
      ansible.builtin.service:
        name: "{{ sftpgo_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure SFTPGo systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ sftpgo_identifier }}.service"
        state: absent

    - name: Ensure SFTPGo support files do not exist
      ansible.builtin.file:
        path: "{{ sftpgo_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels

    - name: Ensure SFTPGo image source files path does not exist
      ansible.builtin.file:
        path: "{{ sftpgo_container_image_self_build_src_files_path }}"
        state: absent

    - name: Ensure SFTPGo container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ sftpgo_container_network }}"
        state: absent

    - name: Ensure SFTPGo container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ sftpgo_container_network }}
      register: network_deletion_result
      changed_when: sftpgo_container_network in network_deletion_result.stdout

- name: Check existence of SFTPGo local backups path
  ansible.builtin.stat:
    path: "{{ sftpgo_backups_path }}"
  register: sftpgo_backups_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if SFTPGo local backups remains
  when: sftpgo_backups_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local SFTPGo instance has been removed, backup remains in `" + sftpgo_backups_path + "`. Feel free to delete it."
        ]
      }}

- name: Check existence of SFTPGo local data path
  ansible.builtin.stat:
    path: "{{ sftpgo_data_path }}"
  register: sftpgo_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if SFTPGo local data remains
  when: sftpgo_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local SFTPGo instance has been removed, some old data remains in `" + sftpgo_data_path + "`. Feel free to delete it."
        ]
      }}

- name: Check existence of SFTPGo home path
  ansible.builtin.stat:
    path: "{{ sftpgo_home_path }}"
  register: sftpgo_home_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if SFTPGo home path remains
  when: sftpgo_home_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local SFTPGo instance has been removed, some old data for the SFTPGo system user remains in `" + sftpgo_home_path + "`. Feel free to delete it."
        ]
      }}
